import Head from "next/head";
import { TODO_URL } from "../../constant";
import styles from "../../styles/Home.module.css";

const Details = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-4">
        <div className="row">
          <div className="col col-md-6 offset-md-3 d-flex justify-content-center">
            <div className="card text-center" style={{ width: "18rem" }}>
              <div className="card-body">
                <h5 className="card-title">ID: {props.post.id}</h5>
                <p className="card-text">TITLE: {props.post.title}</p>
                <p className="card-text">
                  STATUS:{" "}
                  {props.post.isComplete ? "Completed" : "Not Completed"}
                </p>
                <a href="#" className="btn btn-primary">
                  Go somewhere
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export async function getServerSideProps({ params }) {
  const res = await fetch(`${TODO_URL}/${params.id}`, { Method: "GET" });

  const post = await res.json();
  if (res.status !== 200) {
    return {
      notFound: true,
    };
  }
  return {
    props: { post },
  };
}

export default Details;
