import Head from "next/head";
import styles from "../styles/Home.module.css";

const About = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About Page</h1>
      </main>

      <footer className={styles.footer}>
        Powered by <b>@Usman</b>
      </footer>
    </div>
  );
};

export default About;
