import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Create = () => {
  const [post, setPost] = useState({
    id: "",
    title: "",
    completed: "",
    userId: 1,
  });

  const handleChange = (e) => {
    if (e.target.type === "checkbox") {
      setPost((currentState) => ({
        ...currentState,
        [e.target.name]: e.target.checked,
      }));
    } else {
      setPost((currentState) => ({
        ...currentState,
        [e.target.name]: e.target.value,
      }));
    }
  };

  const handleSubmit = () => {
    console.log("post", post);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="row">
          <div className="col d-flex justify-content-center mt-4">
            <div className="card text-center bg-info" style={{ width: "30rem" }}>
              <div className="card-body">
                <h5 className="card-title">Create New Todo</h5>
                <p className="card-text">
                  <form>
                    <div className="mb-3">
                      <label htmlFor="exampleInput2" className="form-label">
                        Id
                      </label>
                      <input
                        type="input"
                        name="id"
                        value={post.id}
                        onChange={(e) => handleChange(e)}
                        className="form-control"
                        id="exampleInput2"
                      />
                    </div>
                    <div className="mb-3">
                      <label htmlFor="exampleInput1" className="form-label">
                        Title
                      </label>
                      <input
                        type="input"
                        name="title"
                        value={post.title}
                        onChange={(e) => handleChange(e)}
                        className="form-control"
                        id="exampleInput1"
                        aria-describedby="inputHelp"
                      />
                    </div>
                    <div className="row">
                      <div className="col d-flex justify-content-center">
                        <div className="mb-3 form-check">
                          <input
                            name="completed"
                            checked={post.completed}
                            type="checkbox"
                            onChange={(e) => handleChange(e)}
                            className="form-check-input"
                            id="exampleCheck1"
                          />
                          <label
                            className="form-check-label"
                            htmlFor="exampleCheck1"
                          >
                            Completed
                          </label>
                        </div>
                      </div>
                    </div>
                  </form>
                </p>

                <button
                  type="submit"
                  className="btn btn-primary"
                  onClick={handleSubmit}
                >
                  Submit
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Create;
