import Head from "next/head";
import { useState } from "react";
import { TODO_URL } from "../constant";
import styles from "../styles/Home.module.css";
import Router from "next/router";

const Create = () => {
  const [post, setPost] = useState({
    title: "",
    isComplete: "",
  });

  const handleChange = (e) => {
    if (e.target.type === "checkbox") {
      setPost((currentState) => ({
        ...currentState,
        [e.target.name]: e.target.checked,
      }));
    } else {
      setPost((currentState) => ({
        ...currentState,
        [e.target.name]: e.target.value,
      }));
    }
  };

  const handleSubmit = async () => {
    const res = await fetch(TODO_URL, {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(post),
    });
    Router.push("/");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="row">
          <div className="col d-flex justify-content-center mt-4">
            <div
              className="card text-center shadow-lg p-3 mb-5 bg-white rounded"
              style={{ width: "30rem" }}
            >
              <div className="card-body">
                <h5 className="card-title">Create New Todo</h5>
                <p className="card-text">
                  <form>
                    <div className="mb-3">
                      <label htmlFor="exampleInput1" className="form-label">
                        Title
                      </label>
                      <input
                        type="input"
                        name="title"
                        value={post.title}
                        onChange={(e) => handleChange(e)}
                        className="form-control"
                        id="exampleInput1"
                        aria-describedby="inputHelp"
                      />
                    </div>
                    <div className="row">
                      <div className="col d-flex justify-content-center">
                        <div className="mb-3 form-check">
                          <input
                            name="isComplete"
                            checked={post.isComplete}
                            type="checkbox"
                            onChange={(e) => handleChange(e)}
                            className="form-check-input"
                            id="exampleCheck1"
                          />
                          <label
                            className="form-check-label"
                            htmlFor="exampleCheck1"
                          >
                            isComplete
                          </label>
                        </div>
                      </div>
                    </div>
                  </form>
                </p>

                <button
                  type="submit"
                  className="btn btn-primary"
                  onClick={handleSubmit}
                >
                  Submit
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Create;
